// <auto-generated />
using System;
using ChameleonPhotoredactor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChameleonPhotoredactor.Migrations
{
    [DbContext(typeof(ChameleonDbContext))]
    partial class ChameleonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("ImageExifData")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImageUploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.ImageEdit", b =>
                {
                    b.Property<int>("ImageEditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageEditId"));

                    b.Property<float>("ContrastChange")
                        .HasColumnType("float");

                    b.Property<string>("CropData")
                        .HasColumnType("longtext");

                    b.Property<float>("ExposureChange")
                        .HasColumnType("float");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastEditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("SaturationChange")
                        .HasColumnType("float");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("int");

                    b.HasKey("ImageEditId");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageEdits");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userId"));

                    b.Property<bool>("isTemp")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("userCreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userDisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("userProfilePic")
                        .HasColumnType("longblob");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.UserStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("editCount")
                        .HasColumnType("int");

                    b.Property<int>("exportCount")
                        .HasColumnType("int");

                    b.Property<int>("importCount")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.Image", b =>
                {
                    b.HasOne("ChameleonPhotoredactor.Models.Entities.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.ImageEdit", b =>
                {
                    b.HasOne("ChameleonPhotoredactor.Models.Entities.Image", "Image")
                        .WithMany("Edits")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.UserStats", b =>
                {
                    b.HasOne("ChameleonPhotoredactor.Models.Entities.User", "User")
                        .WithOne("UserStats")
                        .HasForeignKey("ChameleonPhotoredactor.Models.Entities.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.Image", b =>
                {
                    b.Navigation("Edits");
                });

            modelBuilder.Entity("ChameleonPhotoredactor.Models.Entities.User", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("UserStats");
                });
#pragma warning restore 612, 618
        }
    }
}
